package io.github.kxng0109.chatwithdocs.controller;

import io.github.kxng0109.chatwithdocs.model.ChatRequest;
import io.github.kxng0109.chatwithdocs.model.ChatResponse;
import io.github.kxng0109.chatwithdocs.service.ChatService;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

/**
 * Controller that manages chat-related endpoints. Provides functionality to process chat
 * requests and monitor the health of the chat service.
 */
@Slf4j
@RestController
@RequestMapping("/api/chat")
@RequiredArgsConstructor
public class ChatController {
    private final ChatService chatService;

    /**
     * Handles a chat request by processing the input question and returning a response
     * that includes the answer generated by the chat service, along with additional details
     * such as the question and relevant sources.
     *
     * @param chatRequest the chat request containing the user's question and optional parameters
     *                    for processing, such as the number of relevant sources to consider.
     * @return a {@code ResponseEntity} containing a {@code ChatResponse} which includes the
     * generated answer, the original question, relevant source references, and the processing time.
     */
    @PostMapping
    public ResponseEntity<ChatResponse> chat(
            @Valid @RequestBody ChatRequest chatRequest
    ) {
        log.info("Received chat request: {}", chatRequest.question());

        ChatResponse chatResponse = chatService.chat(chatRequest);
        log.info("Response received: {}", chatResponse.answer());
        return ResponseEntity.ok(chatResponse);
    }

    /**
     * Endpoint to check the health status of the chat service.
     *
     * @return a {@code ResponseEntity} containing the string "Chat service is running"
     * indicating that the chat service is operational.
     */
    @GetMapping("/health")
    public ResponseEntity<String> health() {
        return ResponseEntity.ok("Chat service is running");
    }
}
