spring.application.name=chat-with-docs

spring.datasource.url=jdbc:postgresql://localhost:5432/vectordb
spring.datasource.username=${POSTGRES_USERNAME}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.ai.vectorstore.pgvector.index-type=hnsw
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.schema-name=vector_store
spring.ai.vectorstore.pgvector.table-name=vector_store
spring.ai.vectorstore.pgvector.distance-type=cosine_distance

# Options: ollama (default, local), openai (cloud, requires API key), lmstudio(local)
spring.ai.model.timeout=${MODEL_TIMEOUT:30s}
spring.ai.provider=${AI_PROVIDER:ollama}

spring.ai.ollama.base-url=${OLLAMA_BASE_URL:http://localhost:11434}
spring.ai.ollama.chat.options.model=${OLLAMA_CHAT_MODEL:llama3.2:1b}
spring.ai.ollama.chat.options.temperature=${OLLAMA_TEMPERATURE:0.7}
spring.ai.ollama.embedding.options.model=${OLLAMA_EMBEDDING_MODEL:nomic-embed-text:v1.5}

spring.ai.openai.base-url=${OPENAI_BASE_URL:https://api.openai.com/}
spring.ai.openai.api-key=${OPENAI_API_KEY:}
spring.ai.openai.chat.options.model=${OPENAI_CHAT_MODEL:gpt-4o-mini}
spring.ai.openai.chat.options.temperature=${OPENAI_TEMPERATURE:0.7}
spring.ai.openai.embedding.options.model=${OPENAI_EMBEDDING_MODEL:text-embedding-3-small}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

#logging.level.root=DEBUG
logging.level.io.github.kxng0109.chatwithdocs=DEBUG