package io.github.kxng0109.chatwithdocs.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Builder;

import java.util.List;

/**
 * Represents the response returned after processing a chat request.
 * This record is used to encapsulate the output of a chat operation,
 * including the generated answer, relevant sources, the original question,
 * and the processing time in milliseconds.
 *
 * <ul>
 * <li>answer: The textual answer generated by the chat service based on the provided question.</li>
 * <li>sources: A list of source document excerpts or references that were used to generate the answer.</li>
 * <li>question: The original question passed in the chat request.</li>
 * <li>processingTimeMs: The time it took to process the request and generate a response, in milliseconds.</li>
 * </ul>
 */
@Builder
@JsonInclude(JsonInclude.Include.NON_NULL)
public record ChatResponse(
        String answer,

        List<String> sources,

        String question,

        Long processingTimeMs
) {
}
