CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS hstore;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE SCHEMA IF NOT EXISTS vector_store;

GRANT ALL PRIVILEGES ON SCHEMA vector_store TO testuser;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA vector_store TO testuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA vector_store TO testuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA vector_store
    GRANT ALL ON TABLES TO testuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA vector_store
    GRANT ALL ON SEQUENCES TO testuser;